document.addEventListener("DOMContentLoaded", () => {
  const statusEl = document.getElementById("detection-status");
  const noteEl = document.createElement("p");
  noteEl.style.marginTop = "8px";
  noteEl.style.fontSize = "12px";
  noteEl.style.color = "#b35f00"; // dark orange color for warning
  noteEl.textContent = "⚠️ Note: The analysis result is generated by our AI model and may not be 100% accurate. Please use it as a helpful guide, not a definitive judgment.";

  chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
    const activeTab = tabs[0];
    const url = activeTab?.url || "";

    if (url.includes("reddit.com")) {
      statusEl.textContent = "✅ Reddit post detected. Ready to analyze.";
      statusEl.parentNode.appendChild(noteEl);
      statusEl.classList.add("real");
    } else {
      statusEl.textContent = "❌ This is not a Reddit post page.";
      statusEl.classList.add("fake");
    }
    
  });
});
